name: ingo
favicon: null
layout_spectrum: 0.5464141550473869
typography_spectrum: 0.38816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000688'
    - '#000000'
    - '#000055'
    - '#0000ff'
    - '#0000aa'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.6741032812278718
purpose: []
